AaltoSciComp/science-build-configs

- configs/fgci-centos7-generic/spack/build_config.yaml
This PR adds magma@2.5.3 to the build.
As cuda@10.1 does not support gcc@9.2.0, a new compiler gcc@6.5.0 was also added. Other dependencies were explicitly mentioned to avoid creating duplicate packages.
> fgci-centos7-generic: Adding magma to the build.

- configs/aalto-ubuntu1804-dev/anaconda/build_config.yaml
- configs/fgci-centos7-dev/anaconda/build_config.yaml
- Should be only rearrangements to match and non-semantic changes.
- Only possibly questionable action I can notice is `mne` switches
from pip to conda.  @eglerean
> anaconda sync: triton dev -> aalto dev

- configs/fgci-centos7-dev/anaconda/build_config.yaml
- configs/fgci-centos7-generic/anaconda/build_config.yaml
This PR adds nbval to generic build.
> fgci-centos7-generic/anaconda: Adding nbval to generic build

- configs/fgci-centos7-generic/spack/build_config.yaml
This PR adds openmpi@1.6.5 to the build.
> fgci-centos7-generic: Add openmpi@1.6.5 to the build

- configs/fgci-centos7-generic/spack/build_config.yaml
- configs/fgci-centos7-generic/spack/modules.yaml
This PR adds a version of intel-parallel-studio with no Intel MPI (for use with OpenMPI) and adds suffix intelmpi for versions of intel-parallel-studio with Intel MPI.
> intel-parallel-studio-nompi: Adding intel-parallel-studio~mpi to fgci-centos7-generic

- configs/fgci-centos7-generic/spack/build_config.yaml
This PR adds package freesurfer@6.0.0 to the generic build.
> fgci-centos7-generic: freesurfer@6.0.0

- configs/fgci-centos7-generic/anaconda/build_config.yaml
This PR:
- Freezes anaconda/2020-02-tf2*-environments.
- Adds new anaconda/2020-03-tf*-environments with rapidsai.
- Included environments include cupy and cusignal.
- tensorflow-v2 collection now installs tensorflow 2.1.0.
- Old mpich2-package was replaced by mpich, as the other one is old and deprecated.
> fgci-centos7-generic/anaconda/rapidsai: This PR adds new anaconda environments with rapidsai.

- configs/fgci-centos7-generic/spack/build_config.yaml
This PR adds freesurfer@7.1.0 to the build.
> fgci-centos7-generic: Adding freesurfer@7.1.0

- configs/fgci-centos7-generic/anaconda/build_config.yaml
- configs/fgci-cvmfs-centos7-generic/anaconda/build_config.yaml
Multiple changes:
- Switching anaconda/2020-03-tf*-envs to use miniconda as a
starting point as the packages installed by anaconda installer
create unsatisfiable constraints to the solver.
- Adding many packages that were brought by anaconda.
- Removing many anaconda-related packages.
> fgci-centos7-generic/anaconda: Major overhaul of 2020-03-tf*-envs.

- configs/fgci-centos7-generic/anaconda/build_config.yaml
Adding anaconda/2020-05-tf2 with newer version of pytorch to the build.
> fgci-centos7-generic: anaconda/2020-05-tf2

- configs/fgci-centos7-anaconda/anaconda/build_config.yaml
This PR adds torchvision to base anaconda environments.
> fgci-centos7-anaconda: Adding torchvision-package

- configs/fgci-centos7-haswell/spack/build_config.yaml
These packages are already in the dev builds and the user seems happy with these.
https://version.aalto.fi/gitlab/AaltoScienceIT/triton/issues/210
> fgci-centos7-haswell: geant4 & gsl v. 2.6

- configs/fgci-centos7-haswell-dev/spack/build_config.yaml
- configs/fgci-centos7-haswell-dev/spack/packages.yaml
I am unsure if this is the right place to add it, but this is why this is a pull request :)
https://spack.readthedocs.io/en/latest/package_list.html#libxscrnsaver
> adding libxscrnsaver 1.2.2 to fix triton issue 985

- configs/fgci-centos7-haswell/spack/build_config.yaml
This PR adds nvhpc to the default software stack.
> fgci-centos7-haswell: Add nvhpc 21.5 to the software stack

- configs/fgci-centos7-anaconda-dev/anaconda/build_config.yaml
- Jupyter + matplotlib interactive
- This requires jupyterlab >= 3 as it is now, which we don't have yet,
but adding it now prepares for the future.
> fgci-centos7-anaconda-dev: Add ipympl

- configs/fgci-centos7-singularity-dev/singularity/build_config.yaml
adding mriqc from dockerhub, we had it with the old singularity builder I can test it with the new one.
> mriqc with new builder

- configs/fgci-centos7-haswell/spack/build_config.yaml
This PR adds netcdf-cxx4 to the production build.
> fgci-centos7-haswell: Add netcdf-cxx4 to the production build

- configs/fgci-centos7-anaconda/anaconda/build_config.yaml
This PR adds three new environments:
1. `tensorflow/2.6.0` with Tensorflow installed from PIP
2. `pytorch/1.9.1` with pytorch installed from pytorch-channel
3. `rapidsai/21.10` installed from rapidsai-channel
These environments share common packages, but they are incompatible with each other due to conflicting `cudatoolkit` requirements.
> fgci-centos7-anaconda: New environments for tensorflow, pytorch and rapidsai

- configs/fgci-centos7-haswell/spack/build_config.yaml
This PR adds libgd@2.2.4 to the build.
> fgci-centos7-haswell: Add libgd@2.2.4 to the build

- sync.sh
- sync.sh was used to easily diff and move changes between versions
- So you can run e.g. `DIFF=meld bash sync.sh triton` to graphically
merge things over.
> sync.sh: make diff configurable, better documentation

- configs/fgci-centos7-haswell/spack/build_config.yaml
This PR adds intel-oneapi-compilers and intel-oneapi-mkl versions 2021.3.0 to the build.
> fgci-centos7-haswell: Add intel-oneapi-compilers and intel-oneapi-mkl
