AaltoSciComp/science-build-configs

- configs/fgci-centos7-generic/spack/build_config.yaml
This PR adds the scorep-package to the build.
> fgci-centos7-generic/score: Adding scorep-package to the build

- configs/fgci-centos7-dev/spack/modules.yaml
- configs/fgci-centos7-generic/spack/build_config.yaml
- configs/fgci-centos7-generic/spack/modules.yaml
This pull request adds cp2k to the build.
> fgci-centos7-generic: Adding cp2k to the build

- configs/aalto-ubuntu1804-generic/anaconda/build_config.yaml
Adding synced version of anaconda/2020-04-tf2-environment.
> aalto-ubuntu1804-generic/anaconda: Adding new environment anaconda/2020-04-tf2

- configs/fgci-centos7-dev/anaconda/build_config.yaml
I guess the change I did should be enough to have snakemake when doing module load anaconda?
> Adding snakemake to anaconda module

- configs/fgci-centos7-generic/anaconda/build_config.yaml
Adding snakemake pip package to anaconda module
> Adding snakemake (pip) to anaconda

- configs/aalto-ubuntu1804-generic/anaconda/build_config.yaml
Snakemake works for ubuntu dev, it can be added to ubuntu generic
> adding snakemake

- configs/fgci-centos7-generic/spack/build_config.yaml
> fgci-centos7-generic: Adding r@4.0.3 to the build

- configs/fgci-centos7-anaconda/anaconda/build_config.yaml
- configs/fgci-centos7-anaconda/anaconda/config.yaml
- configs/fgci-centos7-anaconda/anaconda/deployment_config.yaml
This PR adds a new environments anaconda/2021-01-tf2 and miniconda/4.9.2 to production.
> fgci-centos7-anaconda: Add a new environment anaconda/2021-01-tf2

- configs/fgci-centos7-anaconda/anaconda/build_config.yaml
Neuroimaging environment works great for me on Triton. Let's put it live!
> Set neuroimaging environment live on Triton

- configs/fgci-centos7-anaconda/anaconda/build_config.yaml
This PR adds a new anaconda environment with various new packages and tensorflow 2.4.
> fgci-centos7-anaconda: Added anaconda/2020-02-tf2

- configs/fgci-centos7-anaconda/anaconda/build_config.yaml
This PR adds webdataset and GUROBI_HOME environment variable to the environment.
> fgci-centos7-anaconda: Adding GUROBI_HOME

- configs/fgci-centos7-haswell/spack/build_config.yaml
- configs/fgci-centos7-haswell/spack/packages.yaml
Syncing configuration changes from development branch to production branch for upcoming spack upstream sync.
> fgci-centos7-haswell: Spack upstream sync of 09-2021

- configs/fgci-centos7-singularity-dev/singularity/build_config.yaml
Trying fsl as a singularity image
> FSL as a singularity image

- configs/fgci-centos7-haswell-dev/spack/packages.yaml
- Test of rclone, will self-merge
> fgci-centos7-haswell-dev: add rclone

- configs/fgci-centos7-singularity/singularity/build_config.yaml
We tested the dev branch at it works. We can now add fmriprep to the production branch
> adding fmriprep to production branch

- configs/fgci-centos7-haswell/spack/build_config.yaml
This commit adds a newer version of suite-sparse to the build.
> fgci-centos7-haswell: Adding newer version of suite-sparse to the build.

- configs/aalto-jupyter-anaconda-dev/anaconda/build_config.yaml
- configs/aalto-jupyter-anaconda-dev/anaconda/config.yaml
- configs/aalto-jupyter-anaconda-dev/anaconda/deployment_config.yaml
- configs/aalto-jupyter-anaconda/anaconda/config.yaml
- configs/aalto-jupyter-anaconda/anaconda/deployment_config.yaml
This PR creates new environments for jupyter setup.
> Jupyter hackthon 2021

- configs/fgci-centos7-haswell/spack/build_config.yaml
This PR adds gcc 11.2.0 to the production build.
> fgci-centos7-haswell: Adding gcc 11.2.0.

- configs/aalto-jupyter-anaconda-dev/anaconda/build_config.yaml
> aalto-jupyter-anaconda-dev: Re-add mne to pip packages

- configs/fgci-centos7-haswell/spack/build_config.yaml
- configs/fgci-centos7-haswell/spack/modules.yaml
This PR adds newer mujoco versions to the production branch.
> fgci-centos7-haswell: Adding newer mujoco versions
